// <auto-generated />
using System;
using System.Text.Json;
using Lodgify.Payments.Stripe.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lodgify.Payments.Stripe.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lodgify.Payments.Stripe.Domain.AccountHistories.AccountHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SetAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WebhookEventStripeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountHistory", (string)null);
                });

            modelBuilder.Entity("Lodgify.Payments.Stripe.Domain.AccountSessions.AccountSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountSession", (string)null);
                });

            modelBuilder.Entity("Lodgify.Payments.Stripe.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ChargesEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ChargesEnabledSetAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ControllerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dashboard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DetailsSubmitted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DetailsSubmittedSetAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fees")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Losses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementCollection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Lodgify.Payments.Stripe.Domain.WebhookEvents.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<JsonDocument>("RawEventData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("WebhookEventStripeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventStripeId");

                    b.ToTable("WebhookEvent", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
